First review
AlexR1712/js-stack-from-scratch pull request #3
Opened 2016-11-17 00:49 UTC by JMEspiz

2016-11-17 01:47 UTC, AlexR1712 requested changes
Hola @JMEspiz  estos serian los puntos a tratar en esta sección, Gracias por el aporte.

2016-11-17 01:47 UTC, AlexR1712 commented on tutorial/1-node-npm-yarn-package-json/README.md
> +En vez de correr `node .`  para ejecutar nuestro programa podemos usar un script NPM/Yarn en su lugar para disparar la ejecucín del código. Esto nos dará una buena abstracción para poder usar `yarn s
Hola @JMEspiz Gracias por tu aporte, en esta linea solo faltaría esto

- [ ] La letra **ó** en la parte de :  _disparar la **ejecucín**_ 

Gracias! 👍

2016-11-17 01:47 UTC, AlexR1712 commented on tutorial/1-node-npm-yarn-package-json/README.md
> +**Nota**: Si revisas el archivo `package.json` que esta en este capitulo, verá un script `tutorial-test` en cada capítulo. Estos scripts permiten probar que el capítulo funciona adecuadamente cuando
- [ ] Acento en la palabra **Capítulo**
👍 
 perfecto del resto no hay novedad. 
Muchas Gracias por tu aporte. 👍

2016-12-15 13:24 UTC, JMEspiz commented on tutorial/1-node-npm-yarn-package-json/README.md
> +**Nota**: Si revisas el archivo `package.json` que esta en este capitulo, verá un script `tutorial-test` en cada capítulo. Estos scripts permiten probar que el capítulo funciona adecuadamente cuando
Hola Alexander como estas? disculpa la ausencia. Ya hice las correciones y envie el push. Deberia de aperecer. Avisame si tendria que ajustar algo más para pasar a otro capitulo.

Saludos

2016-12-15 15:59 UTC, merged